const ShopActionTypes = {
    FETCH_SHOP_COLLECTIONS_START: "FETCH_SHOP_COLLECTIONS_START",
    FETCH_SHOP_COLLECTIONS_SUCCESS: "FETCH_SHOP_COLLECTIONS_SUCCESS",
    FETCH_SHOP_COLLECTIONS_ERROR: "FETCH_SHOP_COLLECTIONS_ERROR",
};

export default ShopActionTypes;
